language: node_js
node_js:
- '0.12'
- '0.10'
services:
- mongodb
notifications:
  email: false
  slack:
    secure: V3huF7quJs88gpWf0BEuf6FAfPzCDPAU4Y99/UJ58dKFZnuaV0OjEXmIJqliGnsK5r3M7f1K4g8OkU/2CFemMv/Y/9p+NNkjtqB9154j6RhlAZrsouF6Y67h/yZZvlZPt3Txs1/zksMiKmNqloT9HxygHH2+62t4Q1QlijnVal/ftueau6LfbJPz9u5wzwXp/T5VCDxQxbq+lB9++3SKQpRbqjwXPK19cfDa+9x1rksqY0W9I0a6Smty+eRuotHQK38r3NggS4xaWcVXT5MH4tkTzrxfi9/3GnnHiCeb/qRN6fGFkfnCjUCeARYaHciyzVJlYdGIHmo4i7d270YVw1xoLJ6aejK97HnRtZIb8XuBgCud2x7sko3EasP9bjZ6zbTVSx+ZgfsyjvYIzuGuXGDlkOnXfZIjKLUBNugmlbzt6VjgbqOZ7RsanHSgnO2ARdl+Kut1glR/OgGgKk/Z4z6ZGq83z81Sni8fMc5Zkn/68JPmxiqP/3f/mAVJv5yev43cGDSYIHZ/wnk5UGME8pytl36JoeJ7yhg8otMdx0FGCM678qLWXiRoE1BjVoiPFQFfn91rESYeyqyTz2X+yCYc26WnoMtAwcuS09pbDXH9f6tDvE90SSsiWJon/ARQiRDsTHcXX6HLGpVtl9nBhvGYK84lKC/+4J2+P23JFu0=
deploy:
  provider: npm
  email: jason@centralping.com
  api_key:
    secure: eGDVkHnKBKJ/vOQMKHrd8pa1t5wf7xyBmqdeQdUpvvm/b05HPxkzSz2f/G/aAwhmSdyuUlf8VeKT349yXdeGmZI/tvhtNywndetTavSkva6NZMjb4oCslu2bCHrmwekYFoB3HMh7ksWn/2QgnhnYDYM5mY+GCSPiGhH6oMSrSqMxaFjoyVeYUwez11H5ac5libCddM4DB65gJnVXWw5HHrMq6PIa5NdROxuzEPFf6XNuBHL8hpn7B44BNIwISULujsSmzyoel+T3u6QUGO23c9yyRdUl3OV1R55lxbkpR0Npp9gyh2Rsm8WmfmwtiTbH8yHjJvlBrLqc/+ElxQq1MxoF5VJMjcLi888vviP/G4eCS5drDtgvD+ukYH0QzNpnYI4C8X9UeBtU2dwFr0asnL24k0Sjd9S3MjLVVM6KfVfTQ3NJ9z7KDQWYFdmYHRh54mCH3abAhIzX8kosq8k5ezQ8hR9LjQIeyUOU0NnmVvuL3djw+Fo+UmMHinyeAGTt40cZtJRQikrV2bvyNPUK3CdTC7cU+bfTUcDR7NQvmQCqiKIgQrl5Y63kpPSLI1jBZPKukJuRlfCTj6gU0owOOoVNrOB+r7jC1XrHZ53dl64PE43J/64nsCOANyPQnfS+g31HtgOvU7TMne1VeinKrJ8Khn5Qn5KsUAXpGvLnnkU=
  on:
    tags: true
    repo: CentralPing/mongoose-plugin-resource
